# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 887aaa83f9edd404c108c78c7352ef6b5b9ea530e9aa769c6261565d12ca312b3429617235f8e67594dede535393e703246739ce3ca43ef80071b29341aee617

test:
  secret_key_base: d899788de6831519a08c30b7568ac821521dcac2e16f09e99505c36a505eb68a6b971e9ebf4650509c3c6e4b53e5e95002119b8b7ca6a0ace255fda34c914bc1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
